import { PrismaClient } from '@prisma/client';

const INTERPRETATIONS = [
  // ─── DESTINY ─────────────────────────────────────────────────────────────────
  {
    category: 'destiny', number: 1,
    title: 'O Pioneiro',
    summary: 'Liderança, independência e originalidade são as forças motrizes desta jornada de vida.',
    description: 'Quem carrega o Destino 1 veio ao mundo para aprender a ser líder de si mesmo antes de liderar outros. Esta é uma trajetória marcada pela necessidade de desenvolver autonomia, criatividade e a coragem de abrir caminhos onde outros ainda não foram.',
    strengths: ['Liderança natural', 'Criatividade e originalidade', 'Determinação', 'Coragem para inovar'],
    challenges: ['Tendência ao egocentrismo', 'Impaciência', 'Dificuldade em delegar'],
    keywords: ['liderança', 'pioneirismo', 'independência', 'coragem'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'destiny', number: 2,
    title: 'O Diplomata',
    summary: 'Cooperação, sensibilidade e harmonia nas relações são o propósito central desta trajetória.',
    description: 'O Destino 2 é a jornada da parceria e da escuta. Quem carrega este número veio para aprender que a força reside na colaboração, não na competição.',
    strengths: ['Sensibilidade emocional', 'Capacidade diplomática', 'Intuição aguçada', 'Paciência'],
    challenges: ['Dependência emocional', 'Dificuldade em tomar decisões', 'Hipersensibilidade'],
    keywords: ['cooperação', 'diplomacia', 'harmonia', 'parceria'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'destiny', number: 3,
    title: 'O Comunicador',
    summary: 'Expressão criativa, alegria e comunicação são o fio condutor desta jornada.',
    description: 'O Destino 3 é a trajetória da palavra, da arte e da capacidade de iluminar o mundo através da expressão. O desafio central é superar a dispersão e o medo de ser visto.',
    strengths: ['Criatividade artística', 'Otimismo', 'Comunicação fluida', 'Versatilidade'],
    challenges: ['Dispersão', 'Superficialidade', 'Dificuldade em concluir projetos'],
    keywords: ['comunicação', 'criatividade', 'alegria', 'expressão'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'destiny', number: 4,
    title: 'O Construtor',
    summary: 'Ordem, disciplina e construção de bases sólidas definem este caminho de vida.',
    description: 'O Destino 4 é a trajetória do trabalho consciente e da responsabilidade. Quem carrega este número veio para aprender que a liberdade se conquista através da disciplina.',
    strengths: ['Disciplina', 'Confiabilidade', 'Praticidade', 'Lealdade'],
    challenges: ['Rigidez', 'Resistência ao novo', 'Perfeccionismo limitante'],
    keywords: ['ordem', 'disciplina', 'construção', 'responsabilidade'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'destiny', number: 5,
    title: 'O Explorador',
    summary: 'Liberdade, mudança e a busca pela experiência plena são o motor desta trajetória.',
    description: 'O Destino 5 é a jornada do movimento e da adaptação. O maior paradoxo do 5 é que a verdadeira liberdade não vem de nunca se comprometer, mas de comprometer-se de forma autêntica.',
    strengths: ['Adaptabilidade', 'Curiosidade intelectual', 'Capacidade de reinvenção', 'Comunicação'],
    challenges: ['Instabilidade', 'Impulsividade', 'Dificuldade com compromissos'],
    keywords: ['liberdade', 'mudança', 'aventura', 'versatilidade'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'destiny', number: 6,
    title: 'O Cuidador',
    summary: 'Responsabilidade afetiva, beleza e serviço à família e comunidade definem este caminho.',
    description: 'O Destino 6 é a trajetória do amor que se expressa no cuidado. O maior perigo do 6 é o martírio: carregar responsabilidades que não são suas e depois ressentir-se.',
    strengths: ['Capacidade de nutrir', 'Senso estético', 'Responsabilidade', 'Lealdade afetiva'],
    challenges: ['Martírio', 'Controle disfarçado de cuidado', 'Perfeccionismo'],
    keywords: ['cuidado', 'família', 'harmonia', 'beleza', 'serviço'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'destiny', number: 7,
    title: 'O Buscador',
    summary: 'Conhecimento, introspecção e a busca pela verdade profunda são o eixo desta trajetória.',
    description: 'O Destino 7 é a jornada do espírito que busca compreender os mistérios da existência. O maior desafio do 7 é o isolamento — a tendência de se recolher quando o mundo parece incompreensível.',
    strengths: ['Capacidade analítica', 'Intuição profunda', 'Busca pela verdade', 'Independência de pensamento'],
    challenges: ['Isolamento', 'Desconfiança excessiva', 'Frieza emocional'],
    keywords: ['conhecimento', 'introspecção', 'análise', 'sabedoria', 'verdade'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'destiny', number: 8,
    title: 'O Realizador',
    summary: 'Poder, abundância e maestria na dimensão material são o propósito desta jornada.',
    description: 'O Destino 8 é a trajetória do poder consciente — aprender a usar a força, a ambição e os recursos materiais como instrumentos de transformação.',
    strengths: ['Capacidade executiva', 'Visão estratégica', 'Resiliência', 'Manifestação de abundância'],
    challenges: ['Obsessão pelo poder', 'Materialismo excessivo', 'Intolerância com a fraqueza'],
    keywords: ['poder', 'abundância', 'realização', 'liderança', 'manifestação'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'destiny', number: 9,
    title: 'O Humanitário',
    summary: 'Compaixão universal, conclusão de ciclos e serviço à humanidade são o fio desta jornada.',
    description: 'O Destino 9 é a trajetória do amor que se expande além do pessoal para abraçar a humanidade. O 9 contém todos os números anteriores.',
    strengths: ['Compaixão profunda', 'Sabedoria intuitiva', 'Generosidade', 'Visão holística'],
    challenges: ['Apego ao passado', 'Dificuldade em estabelecer limites', 'Melancolia'],
    keywords: ['humanidade', 'compaixão', 'sabedoria', 'serviço', 'liberação'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'destiny', number: 11,
    title: 'O Iluminador',
    summary: 'Intuição elevada, iluminação espiritual e inspiração coletiva — Número Mestre.',
    description: 'Número Mestre 11. Quem nasce com este destino veio com uma missão elevada: ser um canal de luz, inspiração e percepção espiritual. A chave é canalizar a intensidade em inspiração genuína.',
    strengths: ['Intuição espiritual', 'Capacidade de inspirar', 'Sensibilidade artística', 'Visão visionária'],
    challenges: ['Alta tensão interna', 'Hipersensibilidade paralisante', 'Dificuldade de aterrar dons'],
    keywords: ['iluminação', 'intuição', 'inspiração', 'mestre', 'espiritualidade'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'destiny', number: 22,
    title: 'O Construtor Mestre',
    summary: 'Construção de legados de impacto universal — Número Mestre.',
    description: 'Número Mestre 22. Integra a visão elevada do 11 com a capacidade construtiva do 4, formando o Arquiteto Mestre. A chave é a disciplina visionária: sonhar grande E executar passo a passo.',
    strengths: ['Visão e execução em grande escala', 'Liderança inspiracional', 'Determinação excepcional'],
    challenges: ['Pressão do próprio potencial', 'Perfeccionismo paralisante', 'Risco de burnout'],
    keywords: ['legado', 'construção', 'impacto', 'mestre', 'manifestação'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'destiny', number: 33,
    title: 'O Mestre do Amor',
    summary: 'Amor incondicional e cura espiritual — Número Mestre mais elevado.',
    description: 'Número Mestre 33. Quem carrega este destino veio como um portador de amor incondicional. O 33 genuíno é aquele que ensina pelo exemplo vivido, não pela palavra. Extremamente raro.',
    strengths: ['Amor incondicional', 'Presença curativa', 'Ensinamento espiritual', 'Compaixão universal'],
    challenges: ['Peso da responsabilidade espiritual', 'Risco de martírio espiritual', 'Isolamento'],
    keywords: ['amor', 'cura', 'mestre', 'espiritualidade', 'compaixão'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  // ─── SOUL ────────────────────────────────────────────────────────────────────
  {
    category: 'soul', number: 1,
    title: 'Alma Independente',
    summary: 'No âmago, há um desejo profundo de ser único, original e autônomo.',
    description: 'A Alma 1 revela que a motivação mais íntima é a de ser o primeiro, o único, o autêntico. Esta pessoa precisa sentir que tem liberdade de escolha e que pode expressar sua individualidade sem restrições.',
    strengths: ['Motivação interna forte', 'Autoconfiança genuína', 'Determinação interior'],
    challenges: ['Solidão voluntária', 'Dificuldade de pedir ajuda', 'Competitividade interna'],
    keywords: ['independência', 'originalidade', 'autonomia', 'autenticidade'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'soul', number: 2,
    title: 'Alma da União',
    summary: 'No âmago, há um desejo profundo de conexão, parceria e harmonia afetiva.',
    description: 'A Alma 2 revela que a necessidade mais íntima é ser amado, aceito e fazer parte de algo. Esta pessoa precisa de relacionamentos harmoniosos para se sentir completa e segura.',
    strengths: ['Profunda necessidade de conexão', 'Sensibilidade como força', 'Intuição relacional'],
    challenges: ['Medo do abandono', 'Dificuldade em ficar sozinho', 'Dependência afetiva'],
    keywords: ['união', 'amor', 'harmonia', 'parceria', 'pertencimento'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'soul', number: 3,
    title: 'Alma da Expressão',
    summary: 'No âmago, há um desejo profundo de se expressar, criar e ser reconhecido.',
    description: 'A Alma 3 revela que a motivação mais íntima é criar, expressar e ser visto. Esta pessoa precisa de espaços de expressão autêntica para se sentir viva.',
    strengths: ['Alegria interior', 'Criatividade genuína', 'Necessidade de expressão'],
    challenges: ['Medo de exposição apesar do desejo de reconhecimento', 'Insegurança criativa'],
    keywords: ['expressão', 'criatividade', 'alegria', 'reconhecimento'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'soul', number: 4,
    title: 'Alma da Segurança',
    summary: 'No âmago, há um desejo profundo de estabilidade, ordem e pertencimento a algo duradouro.',
    description: 'A Alma 4 revela que a necessidade mais íntima é sentir-se seguro, ter bases sólidas e fazer parte de estruturas que durem. Esta pessoa floresce em ambientes previsíveis e organizados.',
    strengths: ['Lealdade profunda', 'Comprometimento genuíno', 'Confiabilidade interna'],
    challenges: ['Medo da mudança', 'Dificuldade em soltar o que não serve mais', 'Rigidez interna'],
    keywords: ['segurança', 'estabilidade', 'ordem', 'lealdade', 'estrutura'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'soul', number: 5,
    title: 'Alma da Liberdade',
    summary: 'No âmago, há um desejo profundo de liberdade, variedade e experiências intensas.',
    description: 'A Alma 5 revela que a motivação mais íntima é sentir-se livre para explorar, experimentar e não ser confinada. Esta pessoa precisa de movimento — físico, intelectual ou espiritual.',
    strengths: ['Sede de vida genuína', 'Abertura ao novo', 'Adaptabilidade interna'],
    challenges: ['Medo do aprisionamento', 'Dificuldade com rotinas', 'Inquietude crônica'],
    keywords: ['liberdade', 'movimento', 'experiência', 'variedade', 'aventura'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'soul', number: 6,
    title: 'Alma do Amor',
    summary: 'No âmago, há um desejo profundo de amar, cuidar e criar harmonia ao redor.',
    description: 'A Alma 6 revela que a motivação mais íntima é amar e ser amado de forma profunda e comprometida. Esta pessoa encontra propósito no cuidado genuíno.',
    strengths: ['Capacidade de amor profundo', 'Vocação para o cuidado', 'Senso estético refinado'],
    challenges: ['Necessidade de aprovação', 'Dificuldade em receber sem dar', 'Perfeccionismo afetivo'],
    keywords: ['amor', 'cuidado', 'harmonia', 'família', 'beleza'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'soul', number: 7,
    title: 'Alma da Sabedoria',
    summary: 'No âmago, há um desejo profundo de compreender os mistérios da existência.',
    description: 'A Alma 7 revela que a motivação mais íntima é compreender — tanto o mundo exterior quanto o interior. Esta pessoa precisa de silêncio e profundidade para se sentir viva.',
    strengths: ['Profundidade intelectual e espiritual', 'Intuição genuína', 'Independência de pensamento'],
    challenges: ['Isolamento como fuga', 'Dificuldade de confiar', 'Frieza emocional'],
    keywords: ['sabedoria', 'mistério', 'introspecção', 'compreensão', 'espiritualidade'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'soul', number: 8,
    title: 'Alma do Poder',
    summary: 'No âmago, há um desejo profundo de poder, conquista e reconhecimento pelo sucesso.',
    description: 'A Alma 8 revela que a motivação mais íntima é conquistar, alcançar e ser reconhecida por sua competência e poder. Esta pessoa é naturalmente motivada por desafios e realizações.',
    strengths: ['Ambição como força', 'Determinação interna', 'Capacidade de liderança natural'],
    challenges: ['Obsessão pelo reconhecimento', 'Dificuldade de se contentar', 'Workaholism'],
    keywords: ['poder', 'conquista', 'ambição', 'realização', 'sucesso'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'soul', number: 9,
    title: 'Alma Universal',
    summary: 'No âmago, há um desejo profundo de contribuir para algo maior que si mesmo.',
    description: 'A Alma 9 revela que a motivação mais íntima é fazer a diferença no mundo, servir à humanidade e deixar um legado de amor. Esta pessoa é naturalmente movida pelo propósito coletivo.',
    strengths: ['Compaixão genuína', 'Sabedoria inata', 'Amor que transcende o pessoal'],
    challenges: ['Perda de si no cuidado do outro', 'Desilusão com a humanidade', 'Dificuldade de receber'],
    keywords: ['humanidade', 'compaixão', 'propósito', 'sabedoria', 'serviço'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'soul', number: 11,
    title: 'Alma Iluminada',
    summary: 'No âmago, há um desejo profundo de inspirar e ser canal de luz espiritual.',
    description: 'A Alma 11 revela uma motivação interior de altíssima frequência: ser instrumento de elevação coletiva. Esta pessoa sente desde cedo que há um chamado espiritual maior do que o cotidiano pode explicar. A realização vem quando o dom intuitivo é aceito e direcionado.',
    strengths: ['Intuição elevada', 'Sensibilidade espiritual genuína', 'Inspiração natural'],
    challenges: ['Ansiedade pelo ideal', 'Dificuldade de aceitar a imperfeição do mundo físico'],
    keywords: ['inspiração', 'espiritualidade', 'canal', 'luz', 'elevação'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'soul', number: 22,
    title: 'Alma do Construtor Mestre',
    summary: 'No âmago, há um desejo profundo de construir legados colosais para a coletividade.',
    description: 'A Alma 22 anseia por grandiosidade com propósito. Há uma motivação interior de construir algo que vai muito além do ego pessoal — legados, sistemas, instituições que sirvam à humanidade por gerações. A realização vem quando disciplina e visão se fundem em ação concreta.',
    strengths: ['Visão colossal', 'Comprometimento com o legado', 'Disciplina interior'],
    challenges: ['Peso do próprio potencial', 'Perfeccionismo que paralisa'],
    keywords: ['legado', 'construção', 'coletivo', 'grandiosidade', 'disciplina'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'soul', number: 33,
    title: 'Alma do Amor Mestre',
    summary: 'No âmago, há um desejo profundo de amar e curar de forma incondicional.',
    description: 'A Alma 33 carrega o impulso mais elevado: amar sem condições e curar pelo exemplo. Há uma motivação íntima de ser instrumento de cura coletiva — não pelo sofrimento, mas pela alegria do amor que se expande. A realização vem quando o amor flui sem ego.',
    strengths: ['Amor incondicional genuíno', 'Vocação de cura', 'Capacidade de ensinamento'],
    challenges: ['Auto-anulação', 'Dificuldade de estabelecer limites saudáveis'],
    keywords: ['amor incondicional', 'cura', 'ensinamento', 'devoção', 'coletivo'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  // ─── PERSONALITY ─────────────────────────────────────────────────────────────
  {
    category: 'personality', number: 1,
    title: 'Personalidade Líder',
    summary: 'Os outros percebem determinação, confiança e uma presença que toma iniciativa.',
    description: 'A Personalidade 1 transmite ao mundo uma imagem de liderança, independência e autoconfiança. As pessoas ao redor tendem a ver este indivíduo como alguém que sabe o que quer e não hesita em agir.',
    strengths: ['Presença marcante', 'Imagem de competência', 'Capacidade de inspirar confiança'],
    challenges: ['Pode parecer arrogante quando inseguro', 'Dificuldade em mostrar vulnerabilidade'],
    keywords: ['liderança', 'confiança', 'iniciativa', 'determinação'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'personality', number: 2,
    title: 'Personalidade Diplomática',
    summary: 'Os outros percebem gentileza, colaboração e uma presença harmoniosa.',
    description: 'A Personalidade 2 transmite ao mundo uma imagem de cooperação, gentileza e diplomacia. As pessoas ao redor tendem a se sentir à vontade na presença deste indivíduo.',
    strengths: ['Presença acolhedora', 'Capacidade de mediar', 'Imagem de confiabilidade'],
    challenges: ['Pode parecer indeciso', 'Dificuldade em mostrar opinião forte'],
    keywords: ['diplomacia', 'gentileza', 'cooperação', 'harmonia'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'personality', number: 3,
    title: 'Personalidade Comunicativa',
    summary: 'Os outros percebem alegria, criatividade e uma presença que anima o ambiente.',
    description: 'A Personalidade 3 transmite ao mundo uma imagem de expressividade, alegria e criatividade. As pessoas ao redor são naturalmente atraídas por essa energia comunicativa.',
    strengths: ['Carisma natural', 'Presença que alegra o ambiente', 'Facilidade de conectar'],
    challenges: ['Pode parecer superficial', 'Dificuldade em ser levado a sério'],
    keywords: ['alegria', 'comunicação', 'expressão', 'criatividade'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'personality', number: 4,
    title: 'Personalidade Confiável',
    summary: 'Os outros percebem seriedade, responsabilidade e uma presença que transmite solidez.',
    description: 'A Personalidade 4 transmite ao mundo uma imagem de confiabilidade, organização e comprometimento. As pessoas ao redor confiam naturalmente neste indivíduo para tarefas importantes.',
    strengths: ['Imagem de confiabilidade', 'Presença que transmite segurança', 'Seriedade positiva'],
    challenges: ['Pode parecer rígido ou sem flexibilidade', 'Dificuldade em mostrar leveza'],
    keywords: ['confiabilidade', 'ordem', 'responsabilidade', 'seriedade'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'personality', number: 5,
    title: 'Personalidade Dinâmica',
    summary: 'Os outros percebem energia, versatilidade e uma presença que traz movimento.',
    description: 'A Personalidade 5 transmite ao mundo uma imagem de dinamismo, adaptabilidade e entusiasmo pela vida. As pessoas ao redor sentem uma energia contagiante na presença deste indivíduo.',
    strengths: ['Energia contagiante', 'Versatilidade percebida', 'Abertura ao mundo'],
    challenges: ['Pode parecer instável ou imprevisível', 'Dificuldade em ser visto como comprometido'],
    keywords: ['dinamismo', 'versatilidade', 'energia', 'liberdade'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'personality', number: 6,
    title: 'Personalidade Amorosa',
    summary: 'Os outros percebem calor, cuidado e uma presença que nutre e protege.',
    description: 'A Personalidade 6 transmite ao mundo uma imagem de calor humano, responsabilidade e beleza. As pessoas ao redor sentem-se cuidadas e seguras na presença deste indivíduo.',
    strengths: ['Presença acolhedora e calorosa', 'Imagem de responsabilidade afetiva', 'Senso estético percebido'],
    challenges: ['Pode ser visto como superprotetor', 'Dificuldade em mostrar limites'],
    keywords: ['calor', 'cuidado', 'harmonia', 'beleza', 'proteção'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'personality', number: 7,
    title: 'Personalidade Misteriosa',
    summary: 'Os outros percebem profundidade, inteligência e uma presença intrigante.',
    description: 'A Personalidade 7 transmite ao mundo uma imagem de inteligência, profundidade e um certo mistério. As pessoas ao redor sentem que há muito mais por descobrir neste indivíduo.',
    strengths: ['Presença intrigante e fascinante', 'Imagem de sabedoria', 'Capacidade de inspirar respeito'],
    challenges: ['Pode parecer frio ou distante', 'Dificuldade em mostrar emoções'],
    keywords: ['mistério', 'profundidade', 'inteligência', 'sabedoria'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'personality', number: 8,
    title: 'Personalidade Poderosa',
    summary: 'Os outros percebem autoridade, competência e uma presença que impõe respeito.',
    description: 'A Personalidade 8 transmite ao mundo uma imagem de poder, competência e autoridade. As pessoas ao redor naturalmente reconhecem a capacidade executiva deste indivíduo.',
    strengths: ['Presença de autoridade natural', 'Imagem de competência e poder', 'Capacidade de liderança percebida'],
    challenges: ['Pode parecer intimidador', 'Dificuldade em mostrar lado humano'],
    keywords: ['poder', 'autoridade', 'competência', 'respeito'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'personality', number: 9,
    title: 'Personalidade Compassiva',
    summary: 'Os outros percebem sabedoria, generosidade e uma presença que acolhe a todos.',
    description: 'A Personalidade 9 transmite ao mundo uma imagem de sabedoria, compaixão e generosidade. As pessoas ao redor sentem que podem compartilhar suas dores com este indivíduo.',
    strengths: ['Presença que acolhe', 'Imagem de sabedoria compassiva', 'Facilidade em criar laços profundos'],
    challenges: ['Pode ser visto como distante do cotidiano', 'Dificuldade em mostrar necessidades próprias'],
    keywords: ['compaixão', 'sabedoria', 'generosidade', 'acolhimento'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'personality', number: 11,
    title: 'Personalidade Inspiradora',
    summary: 'Os outros percebem uma presença carismática, espiritual e magnetizante.',
    description: 'A Personalidade 11 transmite ao mundo uma aura de sensibilidade espiritual e carisma único. As pessoas ao redor sentem algo especial neste indivíduo sem conseguir nomear exatamente o quê — uma luz, uma profundidade, um magnetismo.',
    strengths: ['Magnetismo espiritual', 'Presença inspiradora', 'Capacidade de elevar o ambiente'],
    challenges: ['Hipersensibilidade às energias alheias', 'Dificuldade de manter equilíbrio emocional em público'],
    keywords: ['inspiração', 'carisma espiritual', 'magnetismo', 'sensibilidade'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'personality', number: 22,
    title: 'Personalidade do Grande Construtor',
    summary: 'Os outros percebem grandiosidade, visão e competência excepcional.',
    description: 'A Personalidade 22 transmite ao mundo uma imagem de capacidade excepcional e visão em grande escala. As pessoas ao redor sentem que este indivíduo é capaz de realizar o que parece impossível — e confiam em sua liderança instintivamente.',
    strengths: ['Presença de liderança em grande escala', 'Imagem de capacidade visionária'],
    challenges: ['Pode parecer distante ou imponente', 'Dificuldade de mostrar o lado humano'],
    keywords: ['grandiosidade', 'visão', 'competência', 'liderança mestre'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'personality', number: 33,
    title: 'Personalidade do Amor Mestre',
    summary: 'Os outros percebem generosidade, amor radiante e acolhimento sem julgamento.',
    description: 'A Personalidade 33 transmite ao mundo uma qualidade rara de amor incondicional em ação. As pessoas ao redor se sentem completamente aceitas. Há uma radiância especial que emana — de bondade genuína, não performada.',
    strengths: ['Amor radiante percebido', 'Presença curativa e acolhedora', 'Generosidade visível'],
    challenges: ['Pode ser explorado pela bondade', 'Dificuldade de mostrar limites sem culpa'],
    keywords: ['amor mestre', 'generosidade', 'acolhimento', 'presença curativa'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  // ─── MISSION ─────────────────────────────────────────────────────────────────
  {
    category: 'mission', number: 1,
    title: 'Missão do Pioneiro',
    summary: 'Inaugurar caminhos originais e demonstrar o poder da autonomia.',
    description: 'Quem tem Missão 1 (número de missão calculado pelo nome completo de nascimento) veio para ser um iniciador. Sua contribuição ao mundo é demonstrar que é possível agir com independência e originalidade, abrindo caminhos onde não havia nenhum.',
    strengths: ['Iniciativa', 'Originalidade', 'Coragem de começar'],
    challenges: ['Impaciência para concluir', 'Dificuldade de colaborar'],
    keywords: ['inauguração', 'autonomia', 'pioneirismo', 'originalidade'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'mission', number: 2,
    title: 'Missão do Mediador',
    summary: 'Criar harmonia e servir de ponte entre pessoas e ideias.',
    description: 'A Missão 2 é a do mediador e construtor de harmonia. Esta pessoa veio para unir, reconciliar e demonstrar o poder da cooperação. Sua sensibilidade aguçada é o instrumento perfeito para compreender todos os lados de uma questão.',
    strengths: ['Mediação', 'Empatia', 'Construção de pontes'],
    challenges: ['Submissão', 'Evitar conflitos necessários'],
    keywords: ['mediação', 'cooperação', 'harmonia', 'parceria'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'mission', number: 3,
    title: 'Missão do Comunicador',
    summary: 'Elevar e inspirar pelo poder da palavra, arte e expressão criativa.',
    description: 'A Missão 3 é a da expressão criativa em sua forma mais pura. Esta pessoa veio para enriquecer o mundo com sua arte, comunicação e alegria. A realização vem quando seus dons criativos são usados para elevar e inspirar.',
    strengths: ['Expressividade', 'Carisma', 'Criatividade'],
    challenges: ['Dispersão', 'Inconstância criativa'],
    keywords: ['comunicação', 'arte', 'expressão', 'inspiração', 'alegria'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'mission', number: 4,
    title: 'Missão do Construtor',
    summary: 'Edificar com método, honestidade e perseverança.',
    description: 'A Missão 4 é a de construir estruturas que durem — seja no campo profissional, familiar ou espiritual. Esta pessoa veio para demonstrar que disciplina e trabalho honesto criam resultados que o tempo não apaga.',
    strengths: ['Disciplina', 'Confiabilidade', 'Concretização'],
    challenges: ['Rigidez', 'Dificuldade de aceitar atalhos legítimos'],
    keywords: ['construção', 'método', 'disciplina', 'honestidade', 'base'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'mission', number: 5,
    title: 'Missão do Mensageiro',
    summary: 'Viver com intensidade e transmitir a sabedoria da experiência.',
    description: 'A Missão 5 é a do mensageiro que aprende vivendo. Esta pessoa veio para experimentar a vida em toda sua diversidade e transmitir as lições colhidas, mostrando que é possível prosperar em meio à mudança e à incerteza.',
    strengths: ['Versatilidade', 'Riqueza de perspectivas', 'Adaptabilidade'],
    challenges: ['Superficialidade', 'Fuga das responsabilidades'],
    keywords: ['experiência', 'mensagem', 'liberdade', 'adaptação', 'transmissão'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'mission', number: 6,
    title: 'Missão do Curador',
    summary: 'Curar, nutrir e criar beleza e harmonia ao redor.',
    description: 'A Missão 6 é a do curador e guardião da harmonia. Esta pessoa veio para nutrir — seja pela família, pela arte, pela medicina ou pelo serviço. Sua sensibilidade ao belo e seu amor responsável são seus maiores instrumentos de missão.',
    strengths: ['Amor genuíno', 'Responsabilidade afetiva', 'Senso de beleza'],
    challenges: ['Perfeccionismo', 'Excesso de controle'],
    keywords: ['cura', 'nutrição', 'harmonia', 'responsabilidade', 'beleza'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'mission', number: 7,
    title: 'Missão do Buscador da Verdade',
    summary: 'Pesquisar profundamente e compartilhar conhecimento transformador.',
    description: 'A Missão 7 é a do pesquisador espiritual ou intelectual. Esta pessoa veio para mergulhar nas profundezas da experiência e emergir com verdades que enriquecem a coletividade. A realização vem quando o conhecimento interno se torna ensinamento.',
    strengths: ['Profundidade analítica', 'Intuição', 'Síntese do conhecimento'],
    challenges: ['Isolamento', 'Dificuldade de tornar o conhecimento acessível'],
    keywords: ['verdade', 'pesquisa', 'profundidade', 'sabedoria', 'ensinamento'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'mission', number: 8,
    title: 'Missão do Realizador',
    summary: 'Liderar com poder e ética, criando abundância compartilhada.',
    description: 'A Missão 8 é a do líder realizador — alguém que usa o poder não para dominar, mas para criar riqueza, oportunidades e estrutura para muitos. Esta pessoa veio para demonstrar que é possível aliar ambição, poder e integridade.',
    strengths: ['Liderança executiva', 'Visão estratégica', 'Capacidade de manifestação'],
    challenges: ['Autoritarismo', 'Obsessão por controle e resultados'],
    keywords: ['poder', 'realização', 'abundância', 'ética', 'liderança'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'mission', number: 9,
    title: 'Missão do Filantropo',
    summary: 'Servir à humanidade com amor desapegado e sabedoria acumulada.',
    description: 'A Missão 9 é a do servidor desapegado. Esta pessoa veio para oferecer ao mundo sua sabedoria e compaixão sem esperar reconhecimento. A realização máxima vem quando o serviço flui livremente, sem ego e sem ressentimento.',
    strengths: ['Compaixão profunda', 'Generosidade', 'Sabedoria prática'],
    challenges: ['Ressentimento acumulado', 'Dificuldade de encerrar ciclos'],
    keywords: ['filantropia', 'serviço', 'desapego', 'humanidade', 'sabedoria'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'mission', number: 11,
    title: 'Missão do Inspirador Mestre',
    summary: 'Iluminar e elevar a consciência coletiva como canal espiritual.',
    description: 'A Missão 11 é a mais elevada das missões comuns — quase um número mestre já em si. Esta pessoa veio para ser canal de luz e elevação coletiva, inspirando pela sua simples presença e pela autenticidade do seu caminho espiritual.',
    strengths: ['Inspiração espiritual', 'Intuição como instrumento de missão', 'Carisma elevado'],
    challenges: ['Instabilidade emocional', 'Dificuldade de aterrar os ideais'],
    keywords: ['inspiração', 'canal', 'espiritualidade', 'elevação', 'luz'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'mission', number: 22,
    title: 'Missão do Grande Construtor',
    summary: 'Concretizar visões grandiosas para o benefício permanente da humanidade.',
    description: 'A Missão 22 é a do construtor de legados coletivos — projetos, instituições e sistemas que sirvam à humanidade por gerações. Combina visão espiritual elevada com capacidade prática de execução em escala.',
    strengths: ['Visão em grande escala', 'Disciplina visionária', 'Capacidade de realização colossal'],
    challenges: ['Peso da responsabilidade', 'Medo de não estar à altura da própria grandeza'],
    keywords: ['legado', 'grandiosidade', 'construção mestre', 'coletivo', 'impacto'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
  {
    category: 'mission', number: 33,
    title: 'Missão do Mestre Curador',
    summary: 'Curar e elevar a humanidade pelo amor incondicional em ação.',
    description: 'A Missão 33 é a mais rara e exigente: curar pela presença, ensinamento e amor que não pede nada em troca. Esta pessoa veio como instrumento de cura coletiva — não pelo drama do martírio, mas pela alegria do amor que flui sem restrições e sem ego.',
    strengths: ['Amor incondicional como instrumento de cura', 'Ensinamento pelo exemplo vivido'],
    challenges: ['Auto-anulação', 'Martírio espiritual', 'Exploração pela bondade'],
    keywords: ['amor mestre', 'cura', 'ensinamento', 'coletivo', 'incondicional'],
    reference: 'Numerologia Cabalística - Sonia Café',
  },
];

export async function seedInterpretations(prisma: PrismaClient): Promise<void> {
  for (const interpretation of INTERPRETATIONS) {
    const data = {
      ...interpretation,
      strengths: JSON.stringify(interpretation.strengths),
      challenges: JSON.stringify(interpretation.challenges),
      keywords: JSON.stringify(interpretation.keywords),
    };
    await prisma.interpretation.upsert({
      where: {
        category_number: {
          category: interpretation.category,
          number: interpretation.number,
        },
      },
      update: data,
      create: data,
    });
  }
}
